### ISSUE TITLE
It crashes after 30 seconds 

### ISSUE THREAD

**Issue by Abraya** [suegdu/Discord-Username-Checker#18]
```
Traceback (most recent call last):
  File "/Users/admin/Downloads/Discord-Username-Checker-main/dsv.py", line 346, in <module>
    main()
    ~~~~^^
  File "/Users/admin/Downloads/Discord-Username-Checker-main/dsv.py", line 142, in main
    proc0()
    ~~~~~^^
  File "/Users/admin/Downloads/Discord-Username-Checker-main/dsv.py", line 166, in proc0
    opt2load()
    ~~~~~~~~^^
  File "/Users/admin/Downloads/Discord-Username-Checker-main/dsv.py", line 244, in opt2load
    validate_names(2,usernames)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/admin/Downloads/Discord-Username-Checker-main/dsv.py", line 185, in validate_names
    print(f"{Lb}[!]{Ly} Token {integ_0} went rate limited. Using token index: {integ_0} connected as: {requests.get(sys_url,headers=s_sys_h()).json()['username']}#{requests.get(sys_url,headers=s_sys_h()).json()['discriminator']}")
                                                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'username'

```

**Comment by Abraya** [comment]
Fixed it : One of the tokens was wrong
